name: traffic-light-env
version: 1.0
apps:
    traffic-light-env:
        environment:
            RED_PIN:    12
            YELLOW_PIN:    13
            GREEN_PIN:    18
        command:    /bin/trafficLight